#!/bin/bash

# Set up aliases
echo "" > /etc/profile.d/bash_aliases.sh
echo "alias ls='ls --color=auto'" >> /etc/profile.d/bash_aliases.sh
echo "alias grep='grep --color=auto'" >> /etc/profile.d/bash_aliases.sh
echo "alias fgrep='fgrep --color=auto'" >> /etc/profile.d/bash_aliases.sh
echo "alias egrep='egrep --color=auto'" >> /etc/profile.d/bash_aliases.sh
echo "alias ll='ls -alF'" >> /etc/profile.d/bash_aliases.sh
echo "alias la='ls -A'" >> /etc/profile.d/bash_aliases.sh
echo "alias l='ls -CF'" >> /etc/profile.d/bash_aliases.sh
echo "alias bash='bash --init-file /etc/profile'" >> /etc/profile.d/bash_aliases.sh
echo "alias sudo='sudo '" >> /etc/profile.d/bash_aliases.sh
